### ISSUE TITLE
why best

### ISSUE THREAD

**Issue by superlbr** [Justin-lu/react-redux-antd#1]
rt

**Comment by Justin-lu** [comment]
I will add README and more details for this.

**Comment by superlbr** [comment]
有没有同构的方案

**Comment by Justin-lu** [comment]
正在增加同构方案~

**Comment by superlbr** [comment]
我参考https://github.com/erikras/react-redux-universal-hot-example，自己捣鼓了下，但是功力比较浅，看的不是特别清楚

**Comment by superlbr** [comment]
后台这块，我比较欣赏https://github.com/niyingfeng/antd ，这哥们复用得挺好

**Comment by superlbr** [comment]
哥们，咋最近加班啦？

**Comment by Justin-lu** [comment]
在搞新项目，没时间搞这个啊。

**Comment by superlbr** [comment]
没关系，慢慢来

**Comment by andyhu** [comment]
@superlbr https://github.com/erikras/react-redux-universal-hot-example  这个弄的很麻烦，css要特殊对待，现阶段同构方案都是问题非常多，不是太稳定，建议再等等

**Comment by superlbr** [comment]
这个我试过，atnd的效果可以处来，就是redux思路要慢慢理，战五渣一枚

**Comment by andyhu** [comment]
其实rsjs本身很容易就能实现出一个类似redux的功能，比较适合做单项数据流的类型

**Comment by andyhu** [comment]
抱歉我看错了，我是说 https://github.com/kriasoft/react-starter-kit 这个弄的很麻烦，记错了

**Comment by andyhu** [comment]
另外建议项目里逐步替换掉node-sass该用precss，好处太多

**Comment by superlbr** [comment]
react-starter-kit 就是集大成，东西太多。antd貌似用的less吧

**Comment by andyhu** [comment]
less sass stylus，都不如用precss，可配置和可扩展性很强，兼容未来css语法，速度非常快

**Comment by Justin-lu** [comment]
@andyhu 用上 postcss 之后，用哪种其实都是看个人喜好而已了。node-sass 有时候老是装不了也实在不爽

**Comment by andyhu** [comment]
是的，node-sass又重又慢，速度比precss慢至少10倍以上。precss+postcss目前用着很不错。以前是用cssnext现在precss比较成熟了，基本可以取代其他任何类似的，只是有些人习惯不同，以及现有代码兼容性问题

**Comment by justyy** [comment]
@Justin-lu 用这个脚手架的时候开发环境checkbox无法change。。。。是不是webpack配置的问题呢？

**Comment by Justin-lu** [comment]
@justyy 不是的，是因为 `rc-checkbox` 有bug，需要绑定到 `1.4.0` 版本，稍等，我更新一下。

**Comment by Justin-lu** [comment]
@justyy https://github.com/Justin-lu/react-redux-antd/commit/8ab87eb868d2badd2c129a5fb161d9978ba4d087 Done

**Comment by lyk248** [comment]
@Justin-lu 
yarn install 以后执行 npm run 一定要 sudo 才不会报错，但 npm install 后就不用 sudo，是什么问题？
![image](https://cloud.githubusercontent.com/assets/10151065/21178926/b486fd5e-c22c-11e6-8bd9-00f06fa96c50.png)

**Comment by Justin-lu** [comment]
@lyk248 看一下你的yarn和npm 的权限

```shell
$ which yarn
/usr/local/bin/yarn

# Justin-lu @ Justin-lu in ~/MySelf/st_front on git:master o [20:31:18]
$ ll /usr/local/bin/yarn
lrwxr-xr-x  1 Justin-lu  admin    36B Oct 15 10:43 /usr/local/bin/yarn -> ../lib/node_modules/yarn/bin/yarn.js

```

**Comment by lyk248** [comment]
@Justin-lu 
```
$ ll /usr/local/bin/yarn
lrwxr-xr-x  1 root  admin  36 12 14 16:59 /usr/local/bin/yarn@ -> ../lib/node_modules/yarn/bin/yarn.js

$ ll /usr/local/bin/npm
lrwxr-xr-x  1 nobody  staff  38  9  5 15:26 /usr/local/bin/npm@ -> ../lib/node_modules/npm/bin/npm-cli.js
```

**Comment by Justin-lu** [comment]
那应该统一一下文件的owner，例如
```shell
sudo chown root /usr/local/bin/npm
```
root 比较奇怪

**Comment by lyk248** [comment]
@Justin-lu 嗯，确实是权限问题导致我都要把 sudo 命令带下去，重新设回用户就好了，多谢。
